"""posts snapshots analyses recommendations search embeddings

Revision ID: 0e1a9783a0bb
Revises: 257b8a875354
Create Date: 2026-05-02 17:44:22.850204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1a9783a0bb'
down_revision: Union[str, None] = '257b8a875354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('top_result_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_runs_created_at_desc', 'search_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_runs_embedding_model'), 'search_runs', ['embedding_model'], unique=False)
    op.create_index('ix_search_runs_normalized_query_hash', 'search_runs', ['normalized_query_hash'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False, server_default=sa.text("0")),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'telegram_message_id', name='uq_posts_channel_tg_msg')
    )
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.create_index('ix_posts_channel_posted_at', 'posts', ['channel_id', 'posted_at'], unique=False)
    op.create_index('ix_posts_content_hash', 'posts', ['content_hash'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_channel_id'), 'snapshots', ['channel_id'], unique=False)
    op.create_index('ix_snapshots_channel_sampled_at', 'snapshots', ['channel_id', 'sampled_at'], unique=False)
    op.create_index(op.f('ix_snapshots_kind'), 'snapshots', ['kind'], unique=False)
    op.create_index(op.f('ix_snapshots_sampled_at'), 'snapshots', ['sampled_at'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('analyzer_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, server_default=sa.text("'queued'")),
    sa.Column('input_refs_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(CASE WHEN channel_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN post_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN snapshot_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_analyses_single_subject'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_analyzer', 'analyses', ['analyzer_id'], unique=False)
    op.create_index('ix_analyses_status_created', 'analyses', ['status', 'created_at'], unique=False)
    op.create_table('embeddings_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, server_default=sa.text("0")),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('dims', sa.Integer(), nullable=False),
    sa.Column('qdrant_collection', sa.String(length=256), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=128), nullable=False),
    sa.Column('extras_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding_model', 'qdrant_collection', 'qdrant_point_id', name='uq_emb_model_collection_point'),
    sa.UniqueConstraint('post_id', 'embedding_model', 'chunk_index', name='uq_emb_post_model_chunk')
    )
    op.create_index('ix_embeddings_metadata_collection', 'embeddings_metadata', ['qdrant_collection'], unique=False)
    op.create_index(op.f('ix_embeddings_metadata_post_id'), 'embeddings_metadata', ['post_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_analysis_id', sa.Integer(), nullable=True),
    sa.Column('search_run_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=96), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('dismissal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_analysis', 'recommendations', ['source_analysis_id'], unique=False)
    op.create_index('ix_recommendations_kind_score', 'recommendations', ['recommendation_type', 'relevance_score'], unique=False)
    op.create_index('ix_recommendations_search_run', 'recommendations', ['search_run_id'], unique=False)
    op.add_column(
        "channels",
        sa.Column(
            "sync_status",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("'idle'"),
        ),
    )
    op.add_column('channels', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('channels', sa.Column('subscriber_count', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('extras_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_channels_last_sync_at'), 'channels', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.drop_index(op.f('ix_channels_last_sync_at'), table_name='channels')
    op.drop_column('channels', 'extras_json')
    op.drop_column('channels', 'subscriber_count')
    op.drop_column('channels', 'last_sync_at')
    op.drop_column('channels', 'sync_status')
    op.drop_index('ix_recommendations_search_run', table_name='recommendations')
    op.drop_index('ix_recommendations_kind_score', table_name='recommendations')
    op.drop_index('ix_recommendations_analysis', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_embeddings_metadata_post_id'), table_name='embeddings_metadata')
    op.drop_index('ix_embeddings_metadata_collection', table_name='embeddings_metadata')
    op.drop_table('embeddings_metadata')
    op.drop_index('ix_analyses_status_created', table_name='analyses')
    op.drop_index('ix_analyses_analyzer', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_snapshots_sampled_at'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_kind'), table_name='snapshots')
    op.drop_index('ix_snapshots_channel_sampled_at', table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_channel_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index('ix_posts_content_hash', table_name='posts')
    op.drop_index('ix_posts_channel_posted_at', table_name='posts')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_search_runs_normalized_query_hash', table_name='search_runs')
    op.drop_index(op.f('ix_search_runs_embedding_model'), table_name='search_runs')
    op.drop_index('ix_search_runs_created_at_desc', table_name='search_runs')
    op.drop_table('search_runs')
    # ### end Alembic commands ###
