"""audit_runs scenario alignment

Revision ID: 15766a843b39
Revises: 0e1a9783a0bb
Create Date: 2026-05-02 17:53:35.297956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15766a843b39'
down_revision: Union[str, None] = '0e1a9783a0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_kind', sa.String(length=64), nullable=False),
    sa.Column(
        'status',
        sa.String(length=32),
        nullable=False,
        server_default=sa.text("'pending'"),
    ),
    sa.Column('raw_user_input_json', sa.JSON(), nullable=True),
    sa.Column('planner_output_json', sa.JSON(), nullable=True),
    sa.Column('quality_gate_json', sa.JSON(), nullable=True),
    sa.Column('result_summary_json', sa.JSON(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_audit_kind'), 'audit_runs', ['audit_kind'], unique=False)
    op.create_index('ix_audit_runs_kind_created', 'audit_runs', ['audit_kind', 'created_at'], unique=False)
    op.create_index('ix_audit_runs_status_created', 'audit_runs', ['status', 'created_at'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column(
        'status',
        sa.String(length=32),
        nullable=False,
        server_default=sa.text("'queued'"),
    ),
    sa.Column('scope_json', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_jobs_status_created', 'export_jobs', ['status', 'created_at'], unique=False)
    op.create_table('audit_run_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_run_id', sa.Integer(), nullable=False),
    sa.Column(
        'entity_kind',
        sa.String(length=32),
        nullable=False,
        server_default=sa.text("'channel'"),
    ),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column(
        'display_order',
        sa.Integer(),
        nullable=False,
        server_default=sa.text('0'),
    ),
    sa.Column('relevance_score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('telegram_username_fallback', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_run_items_audit_rank', 'audit_run_items', ['audit_run_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_audit_run_items_audit_run_id'), 'audit_run_items', ['audit_run_id'], unique=False)
    op.create_index('ix_audit_run_items_channel', 'audit_run_items', ['channel_id'], unique=False)
    op.add_column('channels', sa.Column('invite_slug', sa.String(length=512), nullable=True))
    op.add_column('channels', sa.Column('is_public_accessible', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('last_post_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('channels', sa.Column('posts_per_week_estimate', sa.Float(), nullable=True))
    op.add_column('channels', sa.Column('primary_topic', sa.String(length=512), nullable=True))
    op.add_column('channels', sa.Column('topics_json', sa.JSON(), nullable=True))
    op.add_column('channels', sa.Column('contact_info_json', sa.JSON(), nullable=True))
    op.add_column('channels', sa.Column('language_hint', sa.String(length=32), nullable=True))
    op.add_column('channels', sa.Column('region_country', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_channels_last_post_at'), 'channels', ['last_post_at'], unique=False)
    op.create_index(op.f('ix_channels_primary_topic'), 'channels', ['primary_topic'], unique=False)
    op.add_column('posts', sa.Column('views_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('forwards_count', sa.Integer(), nullable=True))

    # SQLite не поддерживает ADD CONSTRAINT напрямую — перестраиваем таблицу пакетом.
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("seed_channel_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("target_channel_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_recommendations_seed_channel_channels",
            "channels",
            ["seed_channel_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_recommendations_target_channel_channels",
            "channels",
            ["target_channel_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_index(
            op.f("ix_recommendations_seed_channel"),
            ["seed_channel_id"],
            unique=False,
        )
        batch_op.create_index("ix_recommendations_target_channel", ["target_channel_id"], unique=False)
    op.add_column('search_runs', sa.Column('answer_synthesis_json', sa.JSON(), nullable=True))
    op.add_column('search_runs', sa.Column('retrieved_sources_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_runs', 'retrieved_sources_json')
    op.drop_column('search_runs', 'answer_synthesis_json')
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index("ix_recommendations_target_channel")
        batch_op.drop_index(op.f("ix_recommendations_seed_channel"))
        batch_op.drop_constraint("fk_recommendations_target_channel_channels", type_="foreignkey")
        batch_op.drop_constraint("fk_recommendations_seed_channel_channels", type_="foreignkey")
        batch_op.drop_column("target_channel_id")
        batch_op.drop_column("seed_channel_id")
    op.drop_column('posts', 'forwards_count')
    op.drop_column('posts', 'views_count')
    op.drop_index(op.f('ix_channels_primary_topic'), table_name='channels')
    op.drop_index(op.f('ix_channels_last_post_at'), table_name='channels')
    op.drop_column('channels', 'region_country')
    op.drop_column('channels', 'language_hint')
    op.drop_column('channels', 'contact_info_json')
    op.drop_column('channels', 'topics_json')
    op.drop_column('channels', 'primary_topic')
    op.drop_column('channels', 'posts_per_week_estimate')
    op.drop_column('channels', 'last_post_at')
    op.drop_column('channels', 'is_public_accessible')
    op.drop_column('channels', 'invite_slug')
    op.drop_index('ix_audit_run_items_channel', table_name='audit_run_items')
    op.drop_index(op.f('ix_audit_run_items_audit_run_id'), table_name='audit_run_items')
    op.drop_index('ix_audit_run_items_audit_rank', table_name='audit_run_items')
    op.drop_table('audit_run_items')
    op.drop_index('ix_export_jobs_status_created', table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index('ix_audit_runs_status_created', table_name='audit_runs')
    op.drop_index('ix_audit_runs_kind_created', table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_audit_kind'), table_name='audit_runs')
    op.drop_table('audit_runs')
    # ### end Alembic commands ###
